# Generated by Django 4.1.2 on 2022-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('sugerencia', models.CharField(max_length=200)),
            ],
        ),
    ]
