# Generated by Django 4.1.2 on 2022-11-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_final', '0002_sugerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
